### ISSUE TITLE
Tag firing option bug

### ISSUE THREAD

**Issue by gloria-lin-office** [WodenWang820118/gtm-config-generator#70]
[replicate step]
1. manually setup 1 tag in GTM with spec, eg. 
```
window.dataLayer.push({

"event": "navigation_click",
 "business_unit": "$business_unit",
 "nav_category": "$nav_category",
 "nav_label": "$nav_label"

 });
 ```
2. generate the same spec in generator, I was using manual JSON input + download file
3. import the setting, you then can verify the issue

[description]
you will see the tag is noted as modified, but there's no content changed
<img width="935" alt="Screenshot 2024-01-12 at 14 08 17" src="https://github.com/WodenWang820118/gtm-config-generator/assets/71245218/4d4bcd93-95b4-4706-8e44-1900a9cf0ab4">
you will need to go to the edit mode of the tag to see that the tag firing option is empty
<img width="345" alt="Screenshot 2024-01-12 at 14 09 53" src="https://github.com/WodenWang820118/gtm-config-generator/assets/71245218/934cb09d-3149-4b06-a0aa-c060d9c2e293">

[suggested fix]
maybe try to export one correct tag and to check if there's any difference between

**Comment by WodenWang820118** [comment]
Hi, @gloria-lin-office 
I've referenced new config format and added:
```
 tagFiringOption: 'ONCE_PER_EVENT',
      monitoringMetadata: {
        type: 'MAP',
      },
      consentSettings: {
        consentStatus: 'NOT_SET',
      },
```
In the tag setup. After the test, it should work as expected and it no longer has the content changes. Thanks for raising the issue.

**Comment by 55GL** [comment]
tested OK, many thankssssssss
