### ISSUE TITLE
[feature] trim attr name

### ISSUE THREAD

**Issue by 55GL** [WodenWang820118/gtm-config-generator#71]
**description:**
the BAC will very often add space before or after the attr name, it will then result the DLV and event attr to wrongly set

**eg spec (news_category)**
```
window.dataLayer.push({
  "event": "news_view",
  "business_unit": $business_unit,
  "news_name" : "$news_name",
  "news_format" : "$news_format",
  "news_category ": "$news_category"
 });
```
<img width="366" alt="Screenshot 2024-01-12 at 17 58 17" src="https://github.com/WodenWang820118/gtm-config-generator/assets/128343439/8fcc859c-8f9b-4b62-b535-a4753e4322da">

<img width="716" alt="Screenshot 2024-01-12 at 17 58 39" src="https://github.com/WodenWang820118/gtm-config-generator/assets/128343439/00bc4944-6d44-468b-940d-e00a40f6979e">

**target**
1. trim the DLV Data Layer Variable Name filed
2. trim the attr name in event

**Comment by WodenWang820118** [comment]
Hi, @55GL 
The trailing spaces may affect variables and the tag's event parameters, so I did trim them when parsing the spec. Thanks for raising the issue. Let me know if there's any question.
