### ISSUE TITLE
[feature] functionality to change the tracking ID name

### ISSUE THREAD

**Issue by 55GL** [WodenWang820118/gtm-config-generator#76]
[description]
eg. the tracking ID variable originally set to the name "GA4 ID", need to manually update the name in the config file, otherwise the current google tag is taking the GA4 ID than GA4 config and the new ID variable will link to every GA4 tags

[target]
add functionality to change the tracking ID name (Measurement ID -> custom name if set)

**Comment by WodenWang820118** [comment]
Hi, @55GL 
The Google Tag new feature has been released. You may use your own measurement ID or variables with Google Tag Name. For example,
1. if you have an existing `GA4 - Configuration` Google tag
2. there also existed a measurement ID that says, `G-X`

With two input fields filled, we'll modify the existing configurations in GTM after importing it. Also, the used measurement ID will be applied to the created tags. Then, we can abandon the changes made accordingly. Let me know if you have further questions and if so, please open the issue again. Thanks.

Best,
