### ISSUE TITLE
[Bug + feature] scroll and video event name not aligned

### ISSUE THREAD

**Issue by 55GL** [WodenWang820118/gtm-config-generator#77]
[description]
the generated event name is not aligned for scroll event and video event
+ the trigger name for scroll
![Screenshot 2024-01-16 at 16 31 50](https://github.com/WodenWang820118/gtm-config-generator/assets/128343439/97e6ac8f-0ae9-462e-afca-253277b29624)

[target]
current standard for event name ``GA4 event - [event name]``
(if the understand is wrong pls help to correct)
GA4 **Event** - Video -> GA4 **event** - Video
GA4 - scroll -> GA4 event - scroll

current standard for trigger name ``GA4 event - [event name]``
(for this I have question, should we just use ``event - [event name]`` ?)
event scroll -> GA4 event scroll or fix the other names according to the standard

pls help to check if there is sth similar

[example]
(or tick scroll + video event)
```
[
  {
    "event": "scroll",
    "business_unit": "$business_unit",
    "percent_scrolled": "$percent_scrolled"
  },
  {
    "event": "navigation_click",
    "business_unit": "$business_unit",
    "nav_category": "$nav_category",
    "nav_label": "$nav_label"
  },
  {
    "event": "video_start"
  },
  {
    "event": "video_progress"
  },
  {
    "event": "video_completion"
  }
]
```

**Comment by WodenWang820118** [comment]
Hi, @55GL 
The improvement has been released. Thank you for raising the issue.

Best,
